Provides macOS specific starting steps.
codefellows/setup-guide pull request #175
Opened 2022-10-28 19:57 UTC by brookr

2022-10-28 20:01 UTC, kassiebradshaw requested changes
Looks good other than the typo on line 7! wtih instead of with

2022-10-28 20:01 UTC, kassiebradshaw commented on system-setup/mac/README.md
> +Unless it's already in your Dock, the easiest way to open Terminal (which you'll have to do often) is by launching Spotlight Search wtih command-space, and typing "term". You should then be able to h
Typo on line 7, wtih instead of with

2022-10-28 20:04 UTC, brookr commented on system-setup/mac/README.md
> +Unless it's already in your Dock, the easiest way to open Terminal (which you'll have to do often) is by launching Spotlight Search wtih command-space, and typing "term". You should then be able to h
Fixed! Good eye!

2022-10-31 21:15 UTC, kassiebradshaw approved these changes

2022-10-31 21:21 UTC, merged